Fixed #76 - Table update after deleting items
BrunoSilvaATB/coatrack pull request #24
Opened 2021-02-22 07:49 UTC by ChristophBaierATB

Additional optimization: The JavaScript code was moved from within the html documents to the bottom.

2021-03-11 07:58 UTC, BrunoSilvaATB commented
Christoph, have you tested this branch before?
The problem now is that the delete function is using ajax and reload at the same time

2021-03-11 08:09 UTC, BrunoSilvaATB requested changes

2021-03-11 08:09 UTC, BrunoSilvaATB commented on spring-boot/admin/src/main/resources/templates/admin/fragments/api-keys/list.html
>                      },
Please try to put a different duration for hide, so that it doesn't look weird to the user that the page refreshes while the dialog is being close

2021-03-12 09:41 UTC, BrunoSilvaATB commented
Finish first the PR #22 and test it.
After that, if everything is working correctly then please merge it with this PR.

2021-03-23 14:26 UTC, closed without merging

2021-03-23 14:28 UTC, ChristophBaierATB commented
This issue will be solved within #22.